# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh

# Vendor extension library
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.extension_library=/system/lib/libqc-opt.so

# Prebuilt shared libraries
PRODUCT_COPY_FILES += \
    vendor/qcom/system/caf/libv8.so:obj/lib/libv8.so

# Prebuilt CodeAurora libraries
PRODUCT_COPY_FILES += \
    vendor/qcom/system/caf/libv8.so:system/lib/libv8.so \
    vendor/qcom/system/caf/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/qcom/system/caf/libmmosal.so:system/lib/libmmosal.so \
    vendor/qcom/system/caf/libmmparser.so:system/lib/libmmparser.so \
    vendor/qcom/system/caf/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/qcom/system/caf/libqc-opt.so:system/lib/libqc-opt.so

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
    vendor/htc/shooter/proprietary/lib/hw/camera.default.so:obj/lib/hw/camera.default.so


# All the blobs necessary for shooter
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/bin/apph:/system/bin/apph \
    vendor/htc/shooter/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/shooter/proprietary/bin/awb_camera_main:/system/bin/awb_camera_main \
    vendor/htc/shooter/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/shooter/proprietary/bin/cam_ins_spmo:/system/bin/cam_ins_spmo \
    vendor/htc/shooter/proprietary/bin/charging:/system/bin/charging \
    vendor/htc/shooter/proprietary/bin/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \
    vendor/htc/shooter/proprietary/bin/hdmid:/system/bin/hdmid \
    vendor/htc/shooter/proprietary/bin/htcbatt:/system/bin/htcbatt \
    vendor/htc/shooter/proprietary/bin/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/shooter/proprietary/bin/ipd:/system/bin/ipd \
    vendor/htc/shooter/proprietary/bin/ip:/system/bin/ip \
    vendor/htc/shooter/proprietary/bin/load-modem.sh:/system/bin/load-modem.sh \
    vendor/htc/shooter/proprietary/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/shooter/proprietary/bin/mm-abl-daemon:/system/bin/mm-abl-daemon \
    vendor/htc/shooter/proprietary/bin/mm-jps-enc-test:/system/bin/mm-jps-enc-test \
    vendor/htc/shooter/proprietary/bin/mm-mpo-enc-test:/system/bin/mm-mpo-enc-test \
    vendor/htc/shooter/proprietary/bin/mm-qcamera-main-testsuite-client:/system/bin/mm-qcamera-main-testsuite-client \
    vendor/htc/shooter/proprietary/bin/mm-qcamera-main-testsuite-client-awb:/system/bin/mm-qcamera-main-testsuite-client-awb \
    vendor/htc/shooter/proprietary/bin/mm-qcamera-testsuite-client:/system/bin/mm-qcamera-testsuite-client \
    vendor/htc/shooter/proprietary/bin/mm-qcamera-testsuite-client-awb:/system/bin/mm-qcamera-testsuite-client-awb \
    vendor/htc/shooter/proprietary/bin/mmcamera_test:/system/bin/mmcamera_test \
    vendor/htc/shooter/proprietary/bin/mmcamera_test_main:/system/bin/mmcamera_test_main \
    vendor/htc/shooter/proprietary/bin/mpdecision:/system/bin/mpdecision \
    vendor/htc/shooter/proprietary/bin/netmgrd:/system/bin/netmgrd \
    vendor/htc/shooter/proprietary/bin/qmuxd:/system/bin/qmuxd \
    vendor/htc/shooter/proprietary/bin/record:/system/bin/record \
    vendor/htc/shooter/proprietary/bin/recordvideo:/system/bin/recordvideo \
    vendor/htc/shooter/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/shooter/proprietary/bin/sequansd:/system/bin/sequansd \
    vendor/htc/shooter/proprietary/bin/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \
    vendor/htc/shooter/proprietary/bin/sound8x60:/system/bin/sound8x60 \
    vendor/htc/shooter/proprietary/bin/wimaxAddRoute:/system/bin/wimaxAddRoute \
    vendor/htc/shooter/proprietary/bin/wimaxConfigInterface:/system/bin/wimaxConfigInterface \
    vendor/htc/shooter/proprietary/bin/wimaxDaemon:/system/bin/wimaxDaemon \
    vendor/htc/shooter/proprietary/bin/wimaxDhcpRenew:/system/bin/wimaxDhcpRenew \
    vendor/htc/shooter/proprietary/bin/wimaxDhcpRelease:/system/bin/wimaxDhcpRelease \
    vendor/htc/shooter/proprietary/bin/wimaxDumpKmsg:/system/bin/wimaxDumpKmsg \
    vendor/htc/shooter/proprietary/bin/wimaxDumpLogcat:/system/bin/wimaxDumpLogcat \
    vendor/htc/shooter/proprietary/bin/wimaxDumpLastKmsg:/system/bin/wimaxDumpLastKmsg \
    vendor/htc/shooter/proprietary/bin/wimaxFactoryReset:/system/bin/wimaxFactoryReset \
    vendor/htc/shooter/proprietary/bin/wimax_mtd:/system/bin/wimax_mtd \
    vendor/htc/shooter/proprietary/bin/wimax_uart:/system/bin/wimax_uart \
    vendor/htc/shooter/proprietary/bin/wireless_modem:/system/bin/wireless_modem \
    vendor/htc/shooter/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
    vendor/htc/shooter/proprietary/lib/hw/sensors.shooter.so:/system/lib/hw/sensors.shooter.so \
    vendor/htc/shooter/proprietary/lib/libacdbloader.so:/system/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
    vendor/htc/shooter/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
    vendor/htc/shooter/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/shooter/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/shooter/proprietary/lib/libcameraLN.so:system/lib/libcameraLN.so \
    vendor/htc/shooter/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/htc/shooter/proprietary/lib/libcameraSP.so:system/lib/libcameraSP.so \
    vendor/htc/shooter/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/htc/shooter/proprietary/lib/libcryp98.so:/system/lib/libcryp98.so \
    vendor/htc/shooter/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
    vendor/htc/shooter/proprietary/lib/libdll.so:/system/lib/libdll.so \
    vendor/htc/shooter/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/htc/shooter/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
    vendor/htc/shooter/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/shooter/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/shooter/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/shooter/proprietary/lib/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
    vendor/htc/shooter/proprietary/lib/libidl.so:/system/lib/libidl.so \
    vendor/htc/shooter/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
    vendor/htc/shooter/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/htc/shooter/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/htc/shooter/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/shooter/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/htc/shooter/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/shooter/proprietary/lib/libmmjpeg2.so:system/lib/libmmjpeg2.so \
    vendor/htc/shooter/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/htc/shooter/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/htc/shooter/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
    vendor/htc/shooter/proprietary/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
    vendor/htc/shooter/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/htc/shooter/proprietary/lib/libpower.so:/system/lib/libpower.so \
    vendor/htc/shooter/proprietary/lib/libpowermanager.so:/system/lib/libpowermanager.so \
    vendor/htc/shooter/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/shooter/proprietary/lib/liboemcamera_main.so:system/lib/liboemcamera_main.so \
    vendor/htc/shooter/proprietary/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
    vendor/htc/shooter/proprietary/lib/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \
    vendor/htc/shooter/proprietary/lib/libOpenSLES.so:/system/lib/libOpenSLES.so \
    vendor/htc/shooter/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/shooter/proprietary/lib/libqc-opt.so:/system/lib/libqc-opt.so \
    vendor/htc/shooter/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
    vendor/htc/shooter/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
    vendor/htc/shooter/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/htc/shooter/proprietary/etc/AdieHWCodec.csv:/system/etc/AdieHWCodec.csv \
    vendor/htc/shooter/proprietary/etc/AIC3254_REG.csv:/system/etc/AIC3254_REG.csv \
    vendor/htc/shooter/proprietary/etc/AIC3254_REG_DualMic.csv:/system/etc/AIC3254_REG_DualMic.csv \
    vendor/htc/shooter/proprietary/etc/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/shooter/proprietary/etc/CodecDSPID.txt:/system/etc/CodecDSPID.txt \
    vendor/htc/shooter/proprietary/etc/TPA2051_CFG.csv:/system/etc/TPA2051_CFG.csv \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_FM_HP.txt:/system/etc/soundimage/Sound_FM_HP.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_FM_SPK.txt:/system/etc/soundimage/Sound_FM_SPK.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Original.txt:/system/etc/soundimage/Sound_Original.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Original_MFG.txt:/system/etc/soundimage/Sound_Original_MFG.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Original_Recording.txt:/system/etc/soundimage/Sound_Original_Recording.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Original_SPK.txt:/system/etc/soundimage/Sound_Original_SPK.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Phone_Original.txt:/system/etc/soundimage/Sound_Phone_Original.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Phone_Original_HP.txt:/system/etc/soundimage/Sound_Phone_Original_HP.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Phone_Original_REC.txt:/system/etc/soundimage/Sound_Phone_Original_REC.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Phone_Original_SPK.txt:/system/etc/soundimage/Sound_Phone_Original_SPK.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Rec_Landscape.txt:/system/etc/soundimage/Sound_Rec_Landscape.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Rec_mono.txt:/system/etc/soundimage/Sound_Rec_mono.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Recording.txt:/system/etc/soundimage/Sound_Recording.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Rec_Portrait.txt:/system/etc/soundimage/Sound_Rec_Portrait.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/Sound_Rec_Voice_record.txt:/system/etc/soundimage/Sound_Rec_Voice_record.txt \
    vendor/htc/shooter/proprietary/etc/soundimage/srsfx_trumedia_51.cfg:/system/etc/soundimage/srsfx_trumedia_51.cfg \
    vendor/htc/shooter/proprietary/etc/soundimage/srsfx_trumedia_movie.cfg:/system/etc/soundimage/srsfx_trumedia_movie.cfg \
    vendor/htc/shooter/proprietary/etc/soundimage/srsfx_trumedia_music.cfg:/system/etc/soundimage/srsfx_trumedia_music.cfg \
    vendor/htc/shooter/proprietary/etc/soundimage/srs_bypass.cfg:/system/etc/soundimage/srs_bypass.cfg \
    vendor/htc/shooter/proprietary/etc/soundimage/srs_geq10.cfg:/system/etc/soundimage/srs_geq10.cfg \
    vendor/htc/shooter/proprietary/etc/soundimage/srs_global.cfg:/system/etc/soundimage/srs_global.cfg \
    vendor/htc/shooter/proprietary/etc/wimax/sequansd/DefaultTree.xml:/system/etc/wimax/sequansd/DefaultTree.xml \
    vendor/htc/shooter/proprietary/etc/wimax/sequansd/sequansd_app.xml:/system/etc/wimax/sequansd/sequansd_app.xml \
    vendor/htc/shooter/proprietary/etc/wimax/dhcp/wimaxDhcp.conf:/system/etc/wimax/dhcp/wimaxDhcp.conf \
    vendor/htc/shooter/proprietary/framework/wimax.jar:/system/framework/wimax.jar \
    vendor/htc/shooter/proprietary/app/vtt-sprint.apk:/system/app/vtt-sprint.apk

# Prebuilt Adreno 220 libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/etc/firmware/a225_pfp.fw:/system/etc/firmware/a225_pfp.fw \
    vendor/htc/shooter/proprietary/etc/firmware/a225_pm4.fw:/system/etc/firmware/a225_pm4.fw \
    vendor/htc/shooter/proprietary/etc/firmware/a225p5_pm4.fw:/system/etc/firmware/a225p5_pm4.fw \
    vendor/htc/shooter/proprietary/etc/firmware/a300_pfp.fw:/system/etc/firmware/a300_pfp.fw \
    vendor/htc/shooter/proprietary/etc/firmware/a300_pm4.fw:/system/etc/firmware/a300_pm4.fw \
    vendor/htc/shooter/proprietary/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/shooter/proprietary/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/shooter/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/htc/shooter/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
    vendor/htc/shooter/proprietary/lib/egl/egl.cfg:/system/lib/egl/egl.cfg \
    vendor/htc/shooter/proprietary/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/shooter/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/shooter/proprietary/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/shooter/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/shooter/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/shooter/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/shooter/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/shooter/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/shooter/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/shooter/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so
