# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/system/lib/libril.so:obj/lib/libril.so \
    vendor/htc/shooter/system/lib/hw/gps.shooter.so:/obj/lib/hw/gps.shooter.so \
    vendor/htc/shooter/system/lib/hw/lights.msm8660.so:/obj/lib/hw/lights.msm8660.so \
    vendor/htc/shooter/system/lib/hw/sensors.shooter.so:/obj/lib/hw/sensors.shooter.so \
    vendor/htc/shooter/system/lib/libaudcal.so:obj/lib/libaudcal.so \
    vendor/htc/shooter/system/lib/libaudcalwb.so:obj/lib/libaudcalwb.so \
    vendor/htc/shooter/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so
#    vendor/htc/shooter/system/lib/libaudio.so:obj/lib/libaudio.so \
#    vendor/htc/shooter/system/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
#    vendor/htc/shooter/system/lib/libacdbloader.so:obj/lib/libacdbloader.so \
#    vendor/htc/shooter/system/lib/libacdbmapper.so:obj/lib/libacdbmapper.so

# All the blobs necessary for shooter
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/system/bin/agps_rm:/system/etc/agps_rm \
    vendor/htc/shooter/system/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/shooter/system/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/shooter/system/bin/btld:/system/bin/btld \
    vendor/htc/shooter/system/bin/charging:/system/bin/charging \
    vendor/htc/shooter/system/bin/dcvs:/system/bin/dcvs \
    vendor/htc/shooter/system/bin/dcvsd:/system/bin/dcvsd \
    vendor/htc/shooter/system/bin/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/shooter/system/bin/htcbatt:/system/bin/htcbatt \
    vendor/htc/shooter/system/bin/hdmid:/system/bin/hdmid \
    vendor/htc/shooter/system/bin/ipd:/system/bin/ipd \
    vendor/htc/shooter/system/bin/ip:/system/bin/ip \
    vendor/htc/shooter/system/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/shooter/system/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/shooter/system/bin/netmgrd:/system/bin/netmgrd \
    vendor/htc/shooter/system/bin/netsharing:/system/bin/netsharing \
    vendor/htc/shooter/system/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/shooter/system/bin/rild:/system/bin/rild \
    vendor/htc/shooter/system/bin/ser2net:/system/bin/ser2net \
    vendor/htc/shooter/system/bin/sound8x60:/system/bin/sound8x60 \
    vendor/htc/shooter/system/bin/load-modem.sh:/system/bin/load-modem.sh \
    vendor/htc/shooter/system/bin/mpdecision:/system/bin/mpdecision \
    vendor/htc/shooter/system/bin/thermald:/system/bin/thermald \
    vendor/htc/shooter/system/bin/qmuxd:/system/bin/qmuxd \
    vendor/htc/shooter/system/bin/usbnet:/system/bin/usbnet \
    vendor/htc/shooter/system/bin/record:/system/bin/record \
    vendor/htc/shooter/system/bin/recordvideo:/system/bin/recordvideo \
    vendor/htc/shooter/system/xbin/wireless_modem:/system/xbin/wireless_modem \
    vendor/htc/shooter/system/bin/agps_rm:/system/etc/agps_rm \
    vendor/htc/shooter/system/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/shooter/system/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/shooter/system/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/shooter/system/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/shooter/system/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/shooter/system/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/shooter/system/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/shooter/system/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/shooter/system/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/shooter/system/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/shooter/system/lib/libOpenMAXAL.so:/system/lib/libOpenMAXAL.so \
    vendor/htc/shooter/system/lib/libOpenSLES.so:/system/lib/libOpenSLES.so \
    vendor/htc/shooter/system/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/shooter/system/lib/libaudcal.so:/system/lib/libaudcal.so \
    vendor/htc/shooter/system/lib/libaudcalwb.so:/system/lib/libaudcalwb.so \
    vendor/htc/shooter/system/lib/libcameraface.so:/system/lib/libcameraface.so \
    vendor/htc/shooter/system/lib/libcamerapp.so:/system/lib/libcamerapp.so \
    vendor/htc/shooter/system/lib/libdiag.so:/system/lib/libdiag.so \
    vendor/htc/shooter/system/lib/libdll.so:/system/lib/libdll.so \
    vendor/htc/shooter/system/lib/libdsutils.so:/system/lib/libdsutils.so \
    vendor/htc/shooter/system/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/htc/shooter/system/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/shooter/system/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/shooter/system/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/shooter/system/lib/libidl.so:/system/lib/libidl.so \
    vendor/htc/shooter/system/lib/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
    vendor/htc/shooter/system/lib/libmpl.so:/system/lib/libmpl.so \
    vendor/htc/shooter/system/lib/libmpl_jni.so:/system/lib/libmpl_jni.so \
    vendor/htc/shooter/system/lib/libmllite.so:/system/lib/libmllite.so \
    vendor/htc/shooter/system/lib/libmlplatform.so:/system/lib/libmlplatform.so \
    vendor/htc/shooter/system/lib/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/htc/shooter/system/lib/libqdp.so:/system/lib/libqdp.so \
    vendor/htc/shooter/system/lib/libqmi.so:/system/lib/libqmi.so \
    vendor/htc/shooter/system/lib/libqmiservices.so:/system/lib/libqmiservices.so \
    vendor/htc/shooter/system/lib/hw/gps.shooter.so:/system/lib/hw/gps.shooter.so \
    vendor/htc/shooter/system/lib/hw/lights.msm8660.so:/system/lib/hw/lights.msm8660.so \
    vendor/htc/shooter/system/lib/hw/sensors.shooter.so:/system/lib/hw/sensors.shooter.so \
    vendor/htc/shooter/system/framework/wimax-api.jar:/system/framework/wimax-api.jar \
    vendor/htc/shooter/system/app/NovaLauncher.apk:/system/app/NovaLauncher.apk \
    vendor/htc/shooter/system/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/shooter/system/lib/liboemcamera_main.so:/system/lib/liboemcamera_main.so \
    vendor/htc/shooter/system/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/shooter/system/lib/libmmjps.so:/system/lib/libmmjps.so \
    vendor/htc/shooter/system/lib/libmmmpo.so:/system/lib/libmmmpo.so \
    vendor/htc/shooter/system/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/shooter/system/lib/libmmjpeg2.so:/system/lib/libmmjpeg2.so
#    vendor/htc/shooter/system/lib/libacdbloader.so:/system/lib/libacdbloader.so \
#    vendor/htc/shooter/system/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
#    vendor/htc/shooter/system/lib/libaudio.so:/system/lib/libaudio.so \
#    vendor/htc/shooter/system/lib/libaudiopolicy.so:/system/lib/libaudiopolicy.so \
#    vendor/htc/shooter/system/lib/librpc.so:/system/lib/librpc.so
#    vendor/htc/shooter/system/lib/libcamera.so:/system/lib/libcamera.so \
#    vendor/htc/shooter/system/lib/libcameraSP.so:/system/lib/libcameraSP.so \
#    vendor/htc/shooter/system/lib/libcameraLN.so:/system/lib/libcameraLN.so \
