# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh

# Prebuilt libraries that are needed to build camera libraries
PRODUCT_COPY_FILES += \
  vendor/htc/shooter/pyramid/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
  vendor/htc/shooter/pyramid/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/htc/shooter/pyramid/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/shooter/pyramid/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/shooter/pyramid/lib/libcameraservice.so:system/lib/libcameraservice.so \
  vendor/htc/shooter/pyramid/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/shooter/pyramid/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/shooter/pyramid/lib/liboemcamera.so:system/lib/liboemcamera.so \