# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/shooter/proprietary/lib/libcameraLN.so:obj/lib/libcameraLN.so \
    vendor/htc/shooter/proprietary/lib/libcameraSP.so:obj/lib/libcameraSP.so

# All the blobs necessary for shooter
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/shooter/proprietary/lib/libcameraLN.so:/system/lib/libcameraLN.so \
    vendor/htc/shooter/proprietary/lib/libcameraSP.so:/system/lib/libcameraSP.so \
    vendor/htc/shooter/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/shooter/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/shooter/proprietary/lib/libmmjpeg2.so:obj/lib/libmmjpeg2.so \
    vendor/htc/shooter/proprietary/lib/libmmmpo.so:/system/lib/libmmmpo.so \
    vendor/htc/shooter/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so