# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/speedy/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/speedy/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/speedy/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/speedy/proprietary/lib/libwebkitaccel.so:obj/lib/libwebkitaccel.so \
    vendor/htc/speedy/proprietary/lib/libv8.so:obj/lib/libv8.so

# All the blobs necessary for speedy
PRODUCT_COPY_FILES += \
    vendor/htc/speedy/proprietary/app/NovaLauncher.apk:/system/app/NovaLauncher.apk \
    vendor/htc/speedy/proprietary/bin/akmd:/system/bin/akmd \
    vendor/htc/speedy/proprietary/etc/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/speedy/proprietary/bin/awb_camera:/system/bin/awb_camera \
    vendor/htc/speedy/proprietary/bin/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/speedy/proprietary/bin/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/speedy/proprietary/bin/ip:/system/bin/ip \
    vendor/htc/speedy/proprietary/bin/logcat2:/system/bin/logcat2 \
    vendor/htc/speedy/proprietary/bin/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/speedy/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/speedy/proprietary/bin/wimaxDumpKmsg:/system/bin/wimaxDumpKmsg \
    vendor/htc/speedy/proprietary/bin/apph:/system/bin/apph \
    vendor/htc/speedy/proprietary/bin/wimaxDumpLogcat:/system/bin/wimaxDumpLogcat \
    vendor/htc/speedy/proprietary/bin/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \
    vendor/htc/speedy/proprietary/bin/wimax_mtd:/system/bin/wimax_mtd \
    vendor/htc/speedy/proprietary/bin/wimax_uart:/system/bin/wimax_uart \
    vendor/htc/speedy/proprietary/bin/sequansd:/system/bin/sequansd \
    vendor/htc/speedy/proprietary/bin/spkamp:/system/bin/spkamp \
    vendor/htc/speedy/proprietary/bin/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \
    vendor/htc/speedy/proprietary/bin/wimaxDumpLastKmsg:/system/bin/wimaxDumpLastKmsg \
    vendor/htc/speedy/proprietary/bin/wimaxDhcpRenew:/system/bin/wimaxDhcpRenew \
    vendor/htc/speedy/proprietary/bin/wimaxDhcpRelease:/system/bin/wimaxDhcpRelease \
    vendor/htc/speedy/proprietary/bin/wimaxAddRoute:/system/bin/wimaxAddRoute \
    vendor/htc/speedy/proprietary/bin/wimaxConfigInterface:/system/bin/wimaxConfigInterface \
    vendor/htc/speedy/proprietary/etc/AdieHWCodec.csv:/system/etc/AdieHWCodec.csv \
    vendor/htc/speedy/proprietary/etc/TPA2051_CFG.csv:/system/etc/TPA2051_CFG.csv \
    vendor/htc/speedy/proprietary/etc/vomeComp_RTSP.cfg:system/etc/vomeComp_RTSP.cfg \
    vendor/htc/speedy/proprietary/etc/vomeComp.cfg:system/etc/vomeComp.cfg \
    vendor/htc/speedy/proprietary/etc/vomeCore.cfg:system/etc/vomeCore.cfg \
    vendor/htc/speedy/proprietary/etc/vomeplay.cfg:system/etc/vomeplay.cfg \
    vendor/htc/speedy/proprietary/etc/vommcodec.cfg:system/etc/vommcodec.cfg \
    vendor/htc/speedy/proprietary/etc/voPDLog.cfg:system/etc/voPDLog.cfg \
    vendor/htc/speedy/proprietary/etc/voVidDec.dat:system/etc/voVidDec.dat \
    vendor/htc/speedy/proprietary/etc/wimax/DefaultTree.xml:/system/etc/wimax/sequansd/DefaultTree.xml \
    vendor/htc/speedy/proprietary/etc/wimax/sequansd_app.xml:/system/etc/wimax/sequansd/sequansd_app.xml \
    vendor/htc/speedy/proprietary/etc/wimax/wimaxDhcp.conf:/system/etc/wimax/dhcp/wimaxDhcp.conf \
    vendor/htc/speedy/proprietary/framework/wimax-api.jar:/system/framework/wimax-api.jar \
    vendor/htc/speedy/proprietary/lib/hw/gps.speedy.so:/system/lib/hw/gps.speedy.so \
    vendor/htc/speedy/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/speedy/proprietary/lib/libcryp98.so:system/lib/libcryp98.so \
    vendor/htc/speedy/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/speedy/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/speedy/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/speedy/proprietary/lib/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
    vendor/htc/speedy/proprietary/lib/libv8.so:system/lib/libv8.so \
    vendor/htc/speedy/proprietary/lib/libwebkitaccel.so:/system/lib/libwebkitaccel.so \
    vendor/htc/speedy/proprietary/lib/libcameraface.so:/system/lib/libcameraface.so \
    vendor/htc/speedy/proprietary/lib/libcamerapp.so:/system/lib/libcamerapp.so \
    vendor/htc/speedy/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/speedy/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/speedy/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/speedy/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/speedy/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/speedy/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/htc/speedy/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/speedy/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/speedy/proprietary/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/speedy/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/speedy/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/speedy/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/speedy/proprietary/lib/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so
